### ISSUE TITLE
Highlight the latest

### ISSUE THREAD

**Issue by e-minguez** [mvazquezc/openshift-update-graph-viewer#1]
This is super cool and super useful, thanks!

I think it would be nice to highlight the latest one (maybe making it 'preselected' when you choose the channel?) as well as adding links to download the cli tools, etc. (such as I did here https://versions.openshift.tips/ so I can deprecate it :D)

Thanks!

**Comment by mvazquezc** [comment]
Added in commit f353b4ced0048502519b123bec34f58756cb4505
